### PR TITLE
Create model-build-test-ci.yml

### LINKED ISSUE #9: Build CI
Should we add build-ci to the access-esm1.5 branch ?

I think we can just copy https://github.com/ACCESS-NRI/cice5/blob/master/.github/workflows/model-build-test-ci.yml to the branch? (and add access-esm1.5 to the branch names )

@CodeGat  ?

### PR DESCRIPTION
**Pull request by anton-seaice**
Add build CI - closes #9

### CODE REVIEW

**Comment by anton-seaice** [comment]
@CodeGat - how do i specify spack to build with the version "=access-esm1.5" ?

(e.g. https://github.com/ACCESS-NRI/spack-packages/blob/ff2fbc0a9680118a805a0577edbe03008c5346ae/packages/cice4/package.py#L21)

**Comment by CodeGat** [comment]
Hey @anton-seaice - I don't think `build-ci` can do that - it was made before we needed to do LHS/RHS stuff...I'd need to update it to support it

**Comment by anton-seaice** [comment]
Shall i make an issue in the build-ci repo ?

**Comment by CodeGat** [comment]
Yes please!

**Comment by anton-seaice** [comment]
Blocked on https://github.com/ACCESS-NRI/build-ci/issues/183

**Comment by anton-seaice** [comment]
#183 has been implemented, and this builds now. Spack is solving with `access-esm1.5` RHS versions, see https://github.com/ACCESS-NRI/cice4/actions/runs/12363009406/job/34503523792#step:4:98

```
==> Concretized cice4@git.9-build-ci=access-esm1.5%intel@2021.2.0 arch=None-None-x86_64
 -   w6wfuqi  cice4@git.9-build-ci=access-esm1.5%intel@2021.2.0 build_system=makefile arch=linux-rocky8-x86_64
[e]  6bfinv7      ^glibc@2.28%gcc@8.5.0 build_system=autotools arch=linux-rocky8-x86_64
[+]  nql6rht      ^gmake@4.4.1%gcc@8.5.0~guile build_system=generic arch=linux-rocky8-x86_64
...
```

**Comment by anton-seaice** [comment]
Can you approve @CodeGat ?

**Review by CodeGat — APPROVED** [review]

**Review by CodeGat — APPROVED** [review]

**Pull request merged**
